// Generated by CoffeeScript 1.6.2
(function() {
  var ConfigSetting, exports;

  ConfigSetting = (function() {
    function ConfigSetting(template, required) {
      if (typeof template === 'boolean') {
        this.template = '';
        this.required = template;
      } else {
        this.template = template;
        this.required = required;
      }
    }

    ConfigSetting.revive = function(obj) {
      if (!obj) {
        return new ConfigSetting('', true);
      } else if (typeof obj === 'string') {
        return new ConfigSetting(obj, true);
      } else {
        return new ConfigSetting(obj.template, obj.required);
      }
    };

    ConfigSetting.prototype.cryofreeze = function() {
      var frozen;

      if (!this.template && this.required) {
        return null;
      } else if (this.template && this.required) {
        return this.template;
      } else {
        frozen = {};
        if (this.template) {
          frozen.template = this.template;
        }
        if (!this.required) {
          frozen.required = false;
        }
        return frozen;
      }
    };

    return ConfigSetting;

  })();

  exports = module.exports = ConfigSetting;

}).call(this);
