// Generated by CoffeeScript 1.4.0
(function() {
  var mapObject;

  exports.mapObject = mapObject = function(object, callback, context) {
    var key, result, _i, _len, _ref;
    if (!((callback != null) && (object != null))) {
      return object;
    }
    result = {};
    _ref = Object.keys(object);
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      key = _ref[_i];
      result[key] = callback.call(context || value, value, key, object);
    }
    return result;
  };

}).call(this);
