// Generated by CoffeeScript 1.4.0
(function() {
  var ConfigSetting, ZeusService, utils;

  utils = require('./utils');

  ConfigSetting = require('./configsetting');

  module.exports = ZeusService = (function() {

    function ZeusService(type, config) {
      this.type = type;
      this.config = config;
    }

    ZeusService.revive = function(obj) {
      return new ZeusService(obj.type, utils.mapObject(obj.config, ConfigSetting.revive));
    };

    ZeusService.prototype.cryofreeze = function() {
      return {
        type: this.type,
        config: utils.mapObject(this.config, ConfigSetting.prototype.cryofreeze)
      };
    };

    return ZeusService;

  })();

}).call(this);
