// Generated by CoffeeScript 1.4.0
(function() {
  var ZeusService, Zeusfile, utils;

  utils = require('./utils');

  ZeusService = require('./zeusservice');

  module.exports = Zeusfile = (function() {

    function Zeusfile(name, services) {
      this.name = name;
      this.services = services;
    }

    Zeusfile.revive = function(obj) {
      return new Zeusfile(obj.name, utils.mapObject(obj.services, ZeusService.revive));
    };

    Zeusfile.prototype.cryofreeze = function() {
      return {
        name: this.name,
        services: utils.mapObject(this.services, ZeusService.prototype.cryofreeze)
      };
    };

    return Zeusfile;

  })();

}).call(this);
