// Generated by CoffeeScript 1.6.2
(function() {
  var ZeusService, Zeusfile, exports, utils;

  utils = require('./utils');

  ZeusService = require('./zeusservice');

  Zeusfile = (function() {
    function Zeusfile(name, services) {
      this.name = name;
      this.services = services;
    }

    Zeusfile.revive = obj(function() {
      return new Zeusfile(obj.name, utils.mapObject(obj.services, ZeusService.revive));
    });

    Zeusfile.prototype.cryofreeze = function() {
      return {
        name: this.name,
        services: utils.mapObject(this.services, ZeusService.prototype.cryofreeze)
      };
    };

    return Zeusfile;

  })();

  exports = module.exports = Zeusfile;

}).call(this);
