// Generated by CoffeeScript 1.6.2
(function() {
  var ConfigSetting, ZeusService, exports, utils;

  utils = require('./utils');

  ConfigSetting = require('./configsetting');

  ZeusService = (function() {
    function ZeusService(type, config) {
      this.type = type;
      this.config = config;
    }

    ZeusService.revive = obj(function() {
      return new ZeusService(obj.type, utils.mapObject(obj.config, ConfigSetting.revive));
    });

    ZeusService.prototype.cryofreeze = function() {
      return {
        type: this.type,
        config: utils.mapObject(this.config, ConfigSetting.prototype.cryofreeze)
      };
    };

    return ZeusService;

  })();

  exports = module.exports = ZeusService;

}).call(this);
