// Generated by CoffeeScript 1.4.0
(function() {
  var zeus;

  zeus = require('zeus');

  exports.init = function(ui) {
    var app, init, log;
    log = ui.cli.output;
    app = ui.cli.category('app').description('Commands for managing Zeusfiles');
    init = function(appname, options, cb) {
      return zeus.context(ui, process.cwd(), appname, function(err, context) {
        if (err != null) {
          throw err;
        }
        ui.log.info("Saving new Zeusfile to: " + context.path);
        return context.save(cb);
      });
    };
    return app.command('init <appname>').description('Initializes a new Zeusfile with the specified application name').execute(init);
  };

}).call(this);
