// Generated by CoffeeScript 1.4.0
(function() {
  var fs, path, zeus, _;

  zeus = require('zeus');

  fs = require('fs');

  path = require('path');

  _ = require('underscore');

  exports.init = function(ui) {
    var env, init, log, provision;
    log = ui.cli.output;
    env = ui.cli.category('env').description("Manage environments in which Zeus services can be deployed");
    init = function(name, outputPath, options, cb) {
      if (outputPath == null) {
        outputPath = path.join(process.cwd(), name + '.zeusspec');
      }
      return fs.exists(outputPath, function(exists) {
        if (exists) {
          return log.error("Zeusspec file already exists: " + outputPath);
        } else {
          return zeus.context(ui, process.cwd(), function(err, context) {
            return context.createEnvironment(name, function(err, env) {
              if (err != null) {
                throw err;
              }
              return env.save(outputPath, cb);
            });
          });
        }
      });
    };
    provision = function(spec, service, options, cb) {
      return fs.exists(spec, function(exists) {
        if (!exists) {
          return log.error("Zeusspec file not found: " + spec);
        } else {
          return zeus.context(ui, process.cwd(), function(err, context) {
            if (err != null) {
              throw err;
            }
            return zeus.Environment.load(spec, function(err, env) {
              if (err != null) {
                throw err;
              }
              if (env.services.hasOwnProperty(service)) {
                return context.provision(env, service, cb);
              } else {
                return ui.log.error("Service not defined in the zeusspec: " + service);
              }
            });
          });
        }
      });
    };
    env.command('init <name> [outputPath]').description('Initializes an environment with the specified name').execute(init);
    return env.command('provision <spec> <service>').description('Provisions one of the services defined in a zeusspec file').execute(provision);
  };

}).call(this);
