// Generated by CoffeeScript 1.4.0
(function() {
  var _;

  _ = require('underscore');

  exports.init = function(ui) {
    return ui.cli.command('help [command]').description('Display help for a given command').action(function(name) {
      var args;
      if (!name) {
        return ui.cli.parse(['', '', '-h']);
      } else if (_.findWhere(ui.cli.commands, {
        name: name
      })) {
        return ui.cli.parse(['', '', name, '-h']);
      } else if (!ui.cli.categories[name]) {
        throw new Error('Unknown command name ' + name);
      } else {
        args = ['', ''].concat(ui.cli.rawArgs.slice(4), ['-h']);
        return ui.cli.categories[name].parse(args);
      }
    });
  };

}).call(this);
